version: "3"

services:

  sonarqube:
    container_name: sonar
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/usuario
      SONAR_JDBC_USERNAME: usuario
      SONAR_JDBC_PASSWORD: mipassword
    volumes:
      - /home/ubuntu/environment/datos/sonar/data:/opt/sonarqube/data
      - /home/ubuntu/environment/datos/sonar/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/environment/datos/sonar/logs:/opt/sonarqube/logs
    ports:
      - "8080:9000"

  db:
    container_name:         bbdd_sonar
    image:                  postgres:12
    environment:
      POSTGRES_USER:        usuario
      POSTGRES_PASSWORD:    mipassword
    volumes:
      - /home/ubuntu/environment/datos/postgresql:/var/lib/postgresql
      - /home/ubuntu/environment/datos/postgresql_data:/var/lib/postgresql/data
